version: "3.0"
services:
  math-operations:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "math-operations"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      FORMULA: "{{temperature}} * ( 9 / 5 ) + 32"
      RESULT_LABEL: "temperature"
      NEW_RESULT: "update"
    ports:
      - 80:80
